# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_method',
        ),
    ]
